####extract into outfile and add headers

select 
SettledDate as SummaryDate,
Channel as Channel,
BetslipStatus as BetSlipStatus,
LiveYN as LiveYN,
case when BetType <> 'SGL' then 0 else SelectionId end as SelectionId,
case when BetType <> 'SGL' then 'Combi' else SelectionName end as SelectionName,
case when BetType <> 'SGL' then 0 else MarketId end as MarketId,
case when BetType <> 'SGL' then 'Combi' else MarketName end as MarketName,
case when BetType <> 'SGL' then 0 else EventId end as EventId,
case when BetType <> 'SGL' then 'Combi' else EventName end as EventName,
case when BetType <> 'SGL' then 0 else TypeId end as TypeId,
case when BetType <> 'SGL' then 'Combi' else TypeName end as TypeName,
case when BetType <> 'SGL' then 0 else ClassId end as ClassId,
case when BetType <> 'SGL' then 'Combi' else ClassName end as ClassName,
case when BetType <> 'SGL' then 'Combi' else SportName end as Sport,
AVG(TotalStakeAmt) as TotalStakeAmt,
AVG(TotalStakeAmtBC) as TotalStakeAmtBC,
AVG(CashStakeAmt) as CashStakeAmt,
AVG(CashStakeAmtBC) as CashStakeAmtBC,
AVG(BonusStakeAmt) as BonusStakeAmt,
AVG(BonusStakeAmtBC) as BonusStakeAmtBC,
AVG(BonusBalanceStake) as BonusBalanceStake,
AVG(BonusBalanceStakeBC) as BonusBalanceStakeBC,
AVG(TotalReturn) as TotalReturn,
AVG(TotalReturnBC) as TotalReturnBC,
AVG(CashReturn) as CashReturn,
AVG(CashReturnBC) as CashReturnBC,
AVG(BonusBalanceReturn) as BonusBalanceReturn,
AVG(BonusBalancereturnBC) as BonusBalanceReturnBC,
AVG(TotalRefund) as TotalRefund,
AVG(TotalRefundBC) as TotalRefundBC,
AVG(CashRefund) as CashRefund,
AVG(CashRefundBC) as CashRefundBC,
AVG(BonusBalanceRefund) as BonusBalanceRefund,
AVG(BonusBalanceRefundBC) as BonusBalanceRefundBC,
AVG(TokenRefund) as TokenRefund,
AVG(TokenRefundBC) as TokenRefundBC,
AVG(CashOutStake) as CashOutStake,
AVG(CashOutStakeBC) as CashOutStakeBC,
AVG(CashOutWin) as CashOutWin,
AVG(CashOutWinBC) as CashOutWinBC,
COUNT(DISTINCT BetId) AS TotalBetCount
from fd_settled_bets
#where SettledDate = '2016-02-05'
group by 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15;